# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 81fece3a-55c5-446f-87c8-32d2ae0c7daf-capi-aws-check
  namespace: 81fece3a-55c5-446f-87c8-32d2ae0c7daf
spec:
  template:
    metadata:
      name: 81fece3a-55c5-446f-87c8-32d2ae0c7daf-capi-aws
    spec:
      serviceAccountName: 81fece3a-55c5-446f-87c8-32d2ae0c7daf-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 81fece3a-55c5-446f-87c8-32d2ae0c7daf
        - 81fece3a-55c5-446f-87c8-32d2ae0c7daf
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 81fece3a-55c5-446f-87c8-32d2ae0c7daf-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
